### ISSUE TITLE
Why does this even exist?

### ISSUE THREAD

**Issue by glowiak2** [yessGlory17/programmer-browser#49]
Why does this even exists? A web browser cannot be a website + iframe bundled with embedded chromium (electron).

I am confused

**Comment by yessGlory17** [comment]
I am doing this project especially for myself. I'm producing a simple solution to my own problem. My problem is to read what I need to read while using vscode at the same time. But there are some more features that people want to send me via e-mail. A beta version of the project will be released soon. Most things will be rewritten and problems will be eliminated. If you don't like the project, you don't use it. But there are those who use this project, albeit a small number. Even if no one uses this project, I will continue to develop it because it is useful to me.
